#!/bin/sh

# Do the conversion
/usr/bin/python3 /usr/local/bin/dangerzone.py document-to-pixels
RETURN_CODE=$?
if [ $RETURN_CODE -ne 0 ]; then
    echo ""
    exit $RETURN_CODE
fi

# Move converted files into /dangerzone
/bin/mv /tmp/page-*.rgb /dangerzone
/bin/mv /tmp/page-*.width /dangerzone
/bin/mv /tmp/page-*.height /dangerzone
