#!/bin/sh

# Do the conversion
OCR=$OCR OCR_LANGUAGE=$OCR_LANGUAGE /usr/bin/python3 /usr/local/bin/dangerzone.py pixels-to-pdf
RETURN_CODE=$?
if [ $RETURN_CODE -ne 0 ]; then
    echo ""
    exit $RETURN_CODE
fi

# Move converted files into /safezone
/bin/mv /tmp/safe-output.pdf /safezone
/bin/mv /tmp/safe-output-compressed.pdf /safezone
