# Should be the INDEX DIGEST from an image tagged `bookworm-<DATE>-slim`:
#     https://hub.docker.com/_/debian/tags?name=bookworm-
#
# Tag for this digest: bookworm-20250630-slim
DEBIAN_IMAGE_DIGEST=sha256:6ac2c08566499cc2415926653cf2ed7c3aedac445675a013cc09469c9e118fdd
# Can be bumped to today's date
DEBIAN_ARCHIVE_DATE=20250707
# Can be bumped to the latest date in https://github.com/google/gvisor/tags
GVISOR_ARCHIVE_DATE=20250625
# Can be bumped to the latest version and checksum from https://github.com/ebandal/H2Orestart/releases
H2ORESTART_CHECKSUM=eb68a44961ca84431581df866d19cabc20c65188023e10514185a77c08f28837
H2ORESTART_VERSION=v0.7.4

# Buildkit image (taken from freedomofpress/repro-build)
BUILDKIT_IMAGE="docker.io/moby/buildkit:v0.23.2@sha256:ddd1ca44b21eda906e81ab14a3d467fa6c39cd73b9a39df1196210edcb8db59e"
BUILDKIT_IMAGE_ROOTLESS="docker.io/moby/buildkit:v0.23.2-rootless@sha256:cab936745de5d673465948f1e93ff4d6e372bbe33f218afd3314eba45a6f85a9"
