# Should be the INDEX DIGEST from an image tagged `bookworm-<DATE>-slim`:
#     https://hub.docker.com/_/debian/tags?name=trixie-
#
# Tag for this digest: trixie-20251117-slim
DEBIAN_IMAGE_DIGEST=sha256:9812458f2932ede726468ba07bcb9e51bceb1f0c7f16ee30baa789ccee7cc202
# Can be bumped to today's date
DEBIAN_ARCHIVE_DATE=20251118
# Can be bumped to the latest date in https://github.com/google/gvisor/tags
GVISOR_ARCHIVE_DATE=20251110

# Can be bumped to the latest version and checksum from https://github.com/ebandal/H2Orestart/releases
H2ORESTART_CHECKSUM=c99f2c6585c15329885d87960b8b2fd9f415adf80553de6a6b4076756570e4ac
H2ORESTART_VERSION=v0.7.7

# Buildkit image (taken from freedomofpress/repro-build)
BUILDKIT_IMAGE="docker.io/moby/buildkit:v0.23.2@sha256:ddd1ca44b21eda906e81ab14a3d467fa6c39cd73b9a39df1196210edcb8db59e"
BUILDKIT_IMAGE_ROOTLESS="docker.io/moby/buildkit:v0.23.2-rootless@sha256:cab936745de5d673465948f1e93ff4d6e372bbe33f218afd3314eba45a6f85a9"
