name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - "test/**"
  schedule:
    - cron: "2 0 * * *" # Run every day at 02:00 UTC.
  workflow_dispatch:

permissions:
  packages: write
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Build Dangerzone image
        run: python3 build-image.py

      - name: Load local image for tests
        run: |
          podman load -i container.tar | sed -e 's/Loaded image: //' | tr -d '\n' > tests/share/image-id.txt

      - name: Install dependencies
        run: uv venv && uv pip install -e ".[dev]"

      - name: Run tests
        run: uv run pytest

  build-container-image:
    name: Build, push and sign container image
    uses: ./.github/workflows/build-push.yml
    with:
      registry: "ghcr.io/${{ github.repository_owner }}"
      registry_user: ${{ github.repository_owner }}
      image_name: "dangerzone-testing/${{ github.head_ref || github.ref_name }}/v1"
      reproduce: false
      sign: true
      key_name: "tests/assets/dangerzone-testing"
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}
