name: Scan Container
description: Scans a Dangerzone container image for vulnerabilities
inputs:
  image:
    description: Image to scan
    required: true
  severity-cutoff:
    description: Severity cutoff for the scan
    required: false
    default: critical
  upload-sarif:
    description: Whether to upload the SARIF report
    required: false
    default: false
  sarif-category:
    description: Category for the SARIF report
    required: false
runs:
  using: composite
  steps:
    - name: Scan container image
      uses: anchore/scan-action@v7
      id: scan
      with:
        image: ${{ inputs.image }}
        fail-build: true
        only-fixed: false
        severity-cutoff: ${{ inputs.severity-cutoff }}

    - name: Upload container scan report
      if: ${{ inputs.upload-sarif && !cancelled() }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        category: ${{ inputs.sarif-category }}

    - name: Inspect container scan report
      if: always()
      shell: bash
      run: cat ${{ steps.scan.outputs.sarif }}
