#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys

# Load dangerzone module and resources from the source code tree
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.dangerzone_dev = True

from dangerzone.podman import cli

cli.main()
