name: Bug Report (MacOS)
description: File a bug report for MacOS.
labels: ["bug", "triage"]
projects: ["freedomofpress/dangerzone"]
body:
  - type: markdown
    attributes:
      value: |
        Hi, and thanks for taking the time to open this bug report. 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What was the expected behaviour, and what was the actual behaviour? Can you specify the steps you followed, so that we can reproduce?
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: operating system version
      description: Which version of MacOS do you use? You can follow [this link](https://support.apple.com/en-us/109033) to find out more.
      placeholder: macOS Sequoia 15
    validations:
      required: true
  - type: dropdown
    id: proc-architecture
    attributes:
      label: Processor type
      description: |
        Which kind of processor do you use?

        You can follow [this link](https://support.apple.com/en-us/109033) to find out more.
      options:
        - Intel
        - Apple Silicon
    validations:
      required: true
  - type: textarea
    id: dangerzone-version
    attributes:
      label: Dangerzone version
      description: Which version of Dangerzone are you using?
    validations:
      required: true
  - type: textarea
    id: podman-info
    attributes:
      label: Podman info
      description: |
        Please copy and paste the following commands in your
        terminal, and provide us with the output:

        ```shell
        /Applications/Dangerzone.app/Contents/MacOS/dangerzone-machine start
        /Applications/Dangerzone.app/Contents/MacOS/dangerzone-machine --log-level debug raw version
        /Applications/Dangerzone.app/Contents/MacOS/dangerzone-machine --log-level debug raw info -f 'json'
        /Applications/Dangerzone.app/Contents/MacOS/dangerzone-machine --log-level debug raw images
        /Applications/Dangerzone.app/Contents/MacOS/dangerzone-machine --log-level debug raw run hello-world
        ```

        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Document conversion logs
      description: |

        If the bug occurs during document conversion, we'd like some logs from this process. Please copy and paste the following commands in your terminal, and provide us with the output (replace `/path/to/file` with the path to your document):

        ```bash

        /Applications/Dangerzone.app/Contents/MacOS/dangerzone-cli --debug /path/to/file
        ```

      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: |
        Please provide us with any additional info, such as logs, extra content, that may help us debug this issue.
