FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y file poppler-utils imagemagick ghostscript tesseract-ocr

# TODO: when we support OCR in other languages, we need tesseract-ocr-all

# Fix imagemagick policy to allow writing PDFs
RUN sed -i '/rights="none" pattern="PDF"/c\<policy domain="coder" rights="read|write" pattern="PDF" />' /etc/ImageMagick-6/policy.xml

COPY document-to-pixels /usr/local/bin/document-to-pixels
COPY pixels-to-pdf /usr/local/bin/pixels-to-pdf
