# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine314"
  config.vm.synced_folder "../dangerzone-converter", "/opt/dangerzone-converter"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    apk update
    apk add alpine-sdk build-base apk-tools alpine-conf busybox fakeroot syslinux xorriso squashfs-tools sudo
    apk add mtools dosfstools grub-efi
    apk add podman p7zip
    echo "user:100000:65536" >> /etc/subuid
    echo "user:100000:65536" >> /etc/subgid
    adduser user -D -G abuild
    echo "%abuild ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/abuild
    sudo -u user abuild-keygen -i -a -n
  SHELL

  # Workaround VirtualBox bug in macOS Monterey
  # https://github.com/hashicorp/vagrant/issues/12557#issuecomment-952026455
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
