# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine313"
  config.vm.synced_folder "../../dangerzone-converter", "/opt/dangerzone-converter"
  config.vm.synced_folder ".", "/opt/build"
  config.vm.provision "shell", inline: <<-SHELL
    apk update
    apk add alpine-sdk build-base apk-tools alpine-conf busybox fakeroot syslinux xorriso squashfs-tools sudo
    apk add mtools dosfstools grub-efi
    apk add p7zip
  SHELL
end
