name: Check branch conformity
on:
  pull_request:
    types: ["opened", "labeled", "unlabeled", "reopened", "synchronize"]

jobs:
  prevent-fixup-commits:
      runs-on: ubuntu-latest
      env:
        target: debian-bookworm
        distro: debian
        version: bookworm
      steps:
        - name: Checkout
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: prevent fixup commits
          run: |
            git fetch origin
            git status
            git log --pretty=format:%s origin/main..HEAD | grep -ie '^fixup\|^wip' && exit 1 || true

  check-changelog:
    runs-on: ubuntu-latest
    name: Ensure CHANGELOG.md is populated for user-visible changes
    steps:
      # Pin the GitHub action to a specific commit that we have audited and know
      # how it works.
      - uses: tarides/changelog-check-action@8f47e0becbfa549e4c82a3f562aa6f90d2c2ee8c
        with:
          changelog: CHANGELOG.md
