name: Scan nightly app and container
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC.
  workflow_dispatch:

jobs:
  security-scan-container:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Download H2Orestart plugin
        run: uvx mazette install h2orestart

      - name: Build container image
        run: |
          python3 ./install/common/build-image.py \
            --debian-archive-date $(date "+%Y%m%d") \
            --runtime docker
          docker load -i share/container.tar

      - name: Get image tag
        id: tag
        run: echo "tag=$(cat share/image-id.txt)" >> $GITHUB_OUTPUT

      - name: Scan container
        uses: ./.github/actions/scan-container
        with:
          image: "ghcr.io/freedomofpress/dangerzone/v1:${{ steps.tag.outputs.tag }}"
          severity-cutoff: critical
          upload-sarif: false

  security-scan-app:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Scan application
        uses: ./.github/actions/scan-app
        with:
          severity-cutoff: critical
          upload-sarif: false
