name: Scan nightly app
on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC.
  workflow_dispatch:

jobs:
  security-scan-app:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Scan application
        uses: ./.github/actions/scan-app
        with:
          severity-cutoff: critical
          upload-sarif: false
