name: Scan released app and container
on:
  schedule:
    - cron: '0 0 * * *' # Run every day at 00:00 UTC.
  workflow_dispatch:

env:
  # Severity cutoff is 'critical' by default, except for the 5th and 20th of
  # month (i.e., biweekly), where we turn it to 'high'.
  SEVERITY_CUTOFF: ${{ github.event_name == 'schedule' && (github.triggering_actor == 'schedule' && (format('{0}', github.event.schedule) == '0 0 5 * *' || format('{0}', github.event.schedule) == '0 0 20 * *')) && 'high' || 'critical' }}

jobs:
  security-scan-container:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-24.04
            arch: i686
          - runs-on: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Scan container
        uses: ./.github/actions/scan-container
        with:
          image: "ghcr.io/freedomofpress/dangerzone/v1:latest"
          severity-cutoff: ${{ env.SEVERITY_CUTOFF }}
          upload-sarif: true
          sarif-category: container-${{ matrix.arch }}

  security-scan-app:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout the latest released tag
        run: |
          # Grab the latest Grype ignore list before git checkout overwrites it.
          cp .grype.yaml .grype.yaml.new
          # Grab the scan code for the GitHub action.
          cp -r .github/actions/scan-app .github/actions/scan-app.new
          VERSION=$(curl https://api.github.com/repos/freedomofpress/dangerzone/releases/latest | jq -r '.tag_name')
          git checkout $VERSION
          # Restore the newest Grype ignore list.
          mv .grype.yaml.new .grype.yaml
          # Restore the GHA action.
          mv .github/actions/scan-app.new .github/actions/scan-app

      - name: Scan application
        uses: ./.github/actions/scan-app
        with:
          severity-cutoff: ${{ env.SEVERITY_CUTOFF }}
          upload-sarif: true
          sarif-category: app
